 close all
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\data\philipp\git\Hameg-interface\Python\HM1007_export-2021_02_23-20_20_26\HM1007_data-2021_02_23-20_20_26.csv
%
% Auto-generated by MATLAB on 24-Feb-2021 08:25:27

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "CH1"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
HMdata = readtable("C:\data\philipp\git\Hameg-interface\Python\HM1007_export-2021_02_24-09_22_58\HM1007_data-2021_02_24-09_22_58.csv", opts);


%% Clear temporary variables
clear opts
figure;
plot (HMdata.time,HMdata.CH1)
T=HMdata.time(2)-HMdata.time(1);
Fs = 1/T;
L = 2048;             % Length of signal
t = (0:L-1)*T;  

Y = fft(HMdata.CH1);
P2 = abs(Y/L);
P1 = P2(1:L/2+1);
P1(2:end-1) = 2*P1(2:end-1);

figure;
f = Fs*(0:(L/2))/L;
stem(f,P1) 
title('Single-Sided Amplitude Spectrum of X(t)')
xlabel('f (Hz)')
ylabel('|P1(f)|')